# Generated by Django 4.0.4 on 2022-05-28 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_favorite_color_alter_todo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
